### ISSUE TITLE
Update for 1.1.0.1? (Anniversary Update)

### ISSUE THREAD

**Issue by Rerric** [tung362/RoR2PVP#11]
Hello! This one of my favorite mods to use in the past. Currently, it doesn't seem to work with the current version of Risk of Rain 2. Was just wondering if, at any point, this mod will be updated for the current version?

Thanks a bunch.

**Comment by tung362** [comment]
Hi, thanks for letting me know that the mod is outdated. I'm currently busy with another project at the moment but I will look into it as soon as I have some free time!

**Comment by tung362** [comment]
The mod is now updated to the Anniversary Update, hope you all enjoy!

Please note that due to the major changes from the Anniversary Update and from the API, this build might be unstable and may contain many bugs so if you encounter any feel free to let me know!

**Comment by Rerric** [comment]
Thank you very much! Will be trying it out, soon!
