### ISSUE TITLE
No Chests Spawing/Chests not giving items

### ISSUE THREAD

**Issue by wizardwags** [tung362/RoR2PVP#4]
When the Custom Interactable Spawing optin is active within the mod, no chests spawn, regardless of the value set in the config. When I go by vanilla chest spawn rates, the chests that do spawn don't give items. I just rolled back the versions of BepInEx and R2API to the recommended versions listed in the ReadMe on thunderstore.io, but nothing fixes the issue. Am I doing something wrong?

**Comment by tung362** [comment]
This is probably due to the mod being outdated. The recommended API version for the mod and the mod itself was built on an older version of the game and due to the recent updates probably isn't supported anymore. I'm currently working on an update to the mod so hang on tight!

**Comment by tung362** [comment]
A new version has been released! Hopefully that fixed your problem, feel free to give me an update if you still run into problems

**Comment by wizardwags** [comment]
Much appreciated, thank you!
