### ISSUE TITLE
Loader non-functional

### ISSUE THREAD

**Issue by makkkDaddy** [tung362/RoR2PVP#7]
Evertime I try to load in as Loader it instead loads me in as a blank model for commando whenever the pvp mod is active

**Comment by tung362** [comment]
Hi!
That blank model of commando is the sniper class, by default the mod forces everyone to play balanced classes (can be configured to play as anything including as mobs within `TeamPVPCustomPlayableCharacters.cfg`). You can play vanilla characters by turning off `Custom Playable Characters` in the voting menu 

![image](https://user-images.githubusercontent.com/14098872/94353401-a2cbfe80-0025-11eb-91b0-e40d4031157d.png)
